BEGIN;
ALTER TABLE "knowledge_base_coverage_issues" DROP CONSTRAINT "coverage_id_refs_id_6ed1f1a3";
ALTER TABLE "knowledge_base_coverage_stances" DROP CONSTRAINT "coverage_id_refs_id_6377cabf";
ALTER TABLE "knowledge_base_coverage_authors" DROP CONSTRAINT "coverage_id_refs_id_db94ac6";
ALTER TABLE "knowledge_base_coverage_candidates" DROP CONSTRAINT "coverage_id_refs_id_5401b85f";
ALTER TABLE "knowledge_base_coverage_tags" DROP CONSTRAINT "coverage_id_refs_id_b2ff926";
ALTER TABLE "knowledge_base_coverage_ads" DROP CONSTRAINT "coverage_id_refs_id_3f561ee4";
ALTER TABLE "knowledge_base_coverage_funders" DROP CONSTRAINT "coverage_id_refs_id_78b897db";
DROP TABLE "knowledge_base_coverage";
DROP TABLE "knowledge_base_coverage_issues";
DROP TABLE "knowledge_base_coverage_stances";
DROP TABLE "knowledge_base_coverage_authors";
DROP TABLE "knowledge_base_coverage_candidates";
DROP TABLE "knowledge_base_coverage_tags";
DROP TABLE "knowledge_base_coverage_ads";
DROP TABLE "knowledge_base_coverage_funders";
DROP TABLE "knowledge_base_adtocandidate";
DROP TABLE "knowledge_base_media";
ALTER TABLE "knowledge_base_ad_markets" DROP CONSTRAINT "ad_id_refs_id_1d0bcc93";
ALTER TABLE "knowledge_base_ad_stances" DROP CONSTRAINT "ad_id_refs_id_29b0e3b7";
ALTER TABLE "knowledge_base_ad_tags" DROP CONSTRAINT "ad_id_refs_id_2a537642";
ALTER TABLE "knowledge_base_ad_broadcast_types" DROP CONSTRAINT "ad_id_refs_id_61d6f7c5";
DROP TABLE "knowledge_base_ad";
DROP TABLE "knowledge_base_ad_markets";
DROP TABLE "knowledge_base_ad_stances";
DROP TABLE "knowledge_base_ad_tags";
DROP TABLE "knowledge_base_ad_broadcast_types";
DROP TABLE "knowledge_base_fundertocandidate";
DROP TABLE "knowledge_base_fundertofunder";
DROP TABLE "knowledge_base_mediaprofile";
ALTER TABLE "knowledge_base_funder_stances" DROP CONSTRAINT "funder_id_refs_id_7aa1591";
DROP TABLE "knowledge_base_funder";
DROP TABLE "knowledge_base_funder_stances";
ALTER TABLE "knowledge_base_candidate_stances" DROP CONSTRAINT "candidate_id_refs_id_338a8619";
DROP TABLE "knowledge_base_candidate";
DROP TABLE "knowledge_base_candidate_stances";
ALTER TABLE "knowledge_base_tag_issues" DROP CONSTRAINT "tag_id_refs_id_78c0b2e9";
DROP TABLE "knowledge_base_tag";
DROP TABLE "knowledge_base_tag_issues";
DROP TABLE "knowledge_base_stance";
DROP TABLE "knowledge_base_source";
DROP TABLE "knowledge_base_mediatype";
DROP TABLE "knowledge_base_market";
ALTER TABLE "knowledge_base_issue_issue_categories" DROP CONSTRAINT "issue_id_refs_id_7d5561bd";
DROP TABLE "knowledge_base_issue";
DROP TABLE "knowledge_base_issue_issue_categories";
ALTER TABLE "knowledge_base_issuecategory" DROP CONSTRAINT "parent_id_refs_id_4f98273d";
DROP TABLE "knowledge_base_issuecategory";
DROP TABLE "knowledge_base_interestgroupcategory";
DROP TABLE "knowledge_base_incumbentchallengerstatus";
DROP TABLE "knowledge_base_broadcasttype";
DROP TABLE "knowledge_base_coveragetype";
DROP TABLE "knowledge_base_connectedorganization";
DROP TABLE "knowledge_base_committeetype";
DROP TABLE "knowledge_base_committeedesignation";
DROP TABLE "knowledge_base_candidatestatus";
DROP TABLE "knowledge_base_author";
COMMIT;
